apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: nitro-node
  name: nitro-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nitro-node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: nitro-node
    spec:
      containers:
        - args:
            - --init.url="https://snapshot.arbitrum.io/mainnet/nitro.tar"
            - --persistent.chain=/arbitrum-node/data/
            - --persistent.global-config=/arbitrum-node/
            - --l1.url= http://<l1-node-IP>:8545
            - --l2.chain-id=42161
            - --http.api=net,web3,eth,debug
            - --http.corsdomain=*
            - --http.addr=0.0.0.0
            - --http.vhosts=*
          image: offchainlabs/nitro-node:v2.0.8-5b9fe9c
          name: nitro-node
          ports:
            - containerPort: 8547
            - containerPort: 8548
          resources: {}
          volumeMounts:
            - mountPath: /arbitrum-node/data/
              name: nitro-node-claim0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nitro-node-claim0
          persistentVolumeClaim:
            claimName: nitro-node-claim0
status: {}
