name: Update Code
on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link to Zip File'
        required: true

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
    - name: Download and Extract Code
      run: |
        curl -L ${{ github.event.inputs.link }} -o code.zip
        unzip code.zip -d /tmp/code
    - name: Update Code in Repository
      uses: jakejarvis/gha-remove-files@master
      with:
        paths: |
          /**
        exclude: |
          /.git/**
    - name: Add New Code
      run: |
        git add .
        git commit -m "Update code from ${{ github.event.inputs.link }}"
        git push
