name: Create release branch
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release branch to be created'
        required: true
        default: 'release-2022.01.0'

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out parent repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Get repository list
        id: repo_list
        run: |
          REPO_LIST=${{ github.event.inputs.repo_list }}
          
          # Set the output variable
          echo "::set-output name=repo_list::${REPO_LIST}"
          
      - name: Create release branch
        run: |
          GIT_URL="https://github.com/anvesh898" # Replace with your GitHub username
          ORG_NAME="gitops" # Replace with your organization name
          RELEASE_NAME=${{ github.event.inputs.release_name }}
          
          REPO_LIST=${{ steps.repo_list.outputs.repo_list }}
          
          for repo in ${REPO_LIST}; do
            if [[ ! -d "$repo" ]]; then
              git clone "${GIT_URL}"/"${ORG_NAME}"/"${repo}" || exit 1
            fi
            cd "${repo}" || { echo "Can not access to ${repo}"; }
            
            git fetch
            
            git checkout develop
            git pull origin develop
            
            git branch "${RELEASE_NAME}"
            git push --set-up
