name: Create release branch
on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: Name of the release branch to create (e.g. release-2022.12.1)
        required: true

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Read repository list
        run: |
          REPO_LIST=$(cat repo_list)
      - name: Create release branch in each repository
        run: |
          # Check that RELEASE_BRANCH is defined and follows the correct format
          if [[ -z "${INPUT_RELEASE_BRANCH_NAME}" ]]; then
            echo "RELEASE_BRANCH variable is empty, please use a proper value (release-202x.xx.x) for RELEASE_BRANCH in the workflow configuration"
            exit 1
          fi
          if [[ ! "${INPUT_RELEASE_BRANCH_NAME}" =~ ^release-[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then 
            echo "RELEASE_BRANCH values does not match release branch name standards, for example: release-2020.10.0"
            exit 1
          fi
          
          for repo in ${REPO_LIST}; do
            git checkout develop
            git pull origin develop
            git checkout -b "${INPUT_RELEASE_BRANCH_NAME}"
            git push --set-upstream origin "${INPUT_RELEASE_BRANCH_NAME}"
          done
