name: Download website images

on:
  workflow_dispatch:
    inputs:
      website-url:
        description: 'Website URL to download images from'
        required: true

jobs:
  download-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create images folder
        run: mkdir images
      - name: Download images
        run: |
          cd images
          wget -nd -r -l 1 -A jpg,jpeg,png,gif ${{ github.event.inputs.website-url }}
      - name: Commit changes
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images/*
          git commit -m "Add downloaded images"
          git push
