name: Prepare release branch

on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: 'Name of the release branch to be created'
        required: true
        default: 'release-2022.01.0'

jobs:
  prepare-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          # Export variables defined in variables.sh
          . "${GITHUB_WORKSPACE}"/variables.sh
      - name: Check release branch name
        run: |
          # Check that the RELEASE_BRANCH variable is not empty
          if [[ -z "${RELEASE_BRANCH}" ]]; then
            echo "Error: RELEASE_BRANCH variable is empty. Please use the 'Run customized...' option and provide a proper value (e.g. release-202x.xx.x) for the RELEASE_BRANCH variable."
            exit 1
          fi
          # Check that the RELEASE_BRANCH variable follows the expected naming convention
          if [[ ! "${RELEASE_BRANCH}" =~ ^release-[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
            echo "Error: RELEASE_BRANCH values does not match release branch name standards. For example: release-2020.10.0"
            exit 1
          fi
      - name: Prepare release branch
        run: |
          # Set up Git
          git config --global user.email 'bamboo@test.com'
          git config --global user.name 'Bamboo test'
          
          # Iterate over the list of repositories
          for repo in ${REPO_LIST}; do
            # Change to the repository directory
            cd "${GITHUB_WORKSPACE}"/"${repo}" || { echo "Error: Could not access repository directory ${GITHUB_WORKSPACE}/${repo}."; }
            
            # Check out the RELEASE_BRANCH and pull the latest changes
            git fetch
            git checkout "${RELEASE_BRANCH}"
            git pull origin "${RELEASE_BRANCH}"
          done
name: Prepare release branch

on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: 'Name of the release branch to be created'
        required: true
        default: 'release-2022.01.0'

jobs:
  prepare-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          # Export variables defined in variables.sh
          . "${GITHUB_WORKSPACE}"/variables.sh
      - name: Check release branch name
        run: |
          # Check that the RELEASE_BRANCH variable is not empty
          if [[ -z "${RELEASE_BRANCH}" ]]; then
            echo "Error: RELEASE_BRANCH variable is empty. Please use the 'Run customized...' option and provide a proper value (e.g. release-202x.xx.x) for the RELEASE_BRANCH variable."
            exit 1
          fi
          # Check that the RELEASE_BRANCH variable follows the expected naming convention
          if [[ ! "${RELEASE_BRANCH}" =~ ^release-[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
            echo "Error: RELEASE_BRANCH values does not match release branch name standards. For example: release-2020.10.0"
            exit 1
          fi
      - name: Prepare release branch
        run: |
          # Set up Git
          git config --global user.email 'bamboo@test.com'
          git config --global user.name 'Bamboo test'
          
          # Iterate over the list of repositories
          for repo in ${REPO_LIST}; do
            # Change to the repository directory
            cd "${GITHUB_WORKSPACE}"/"${repo}" || { echo "Error: Could not access repository directory ${GITHUB_WORKSPACE}/${repo}."; }
            
            # Check out the RELEASE_BRANCH and pull the latest changes
            git fetch
            git checkout "${RELEASE_BRANCH}"
            git pull origin "${RELEASE_BRANCH}"
          done
