name: Download website images

on:
  workflow_dispatch:
    inputs:
      website-url:
        description: 'Website URL to download images from'
        required: true

jobs:
  download-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create images folder
        run: |
           mkdir images
           chmod -R 777 images
      - name: Install pup
        run: |
          curl -L -o pup https://github.com/ericchiang/pup/releases/latest/download/pup_linux_amd64.zip
          unzip pup_linux_amd64.zip
          chmod +x pup
      - name: Download images
        run: |
          cd images
          wget $(curl -s ${{ github.event.inputs.website-url }} | pup 'img[src] attr{src}')
      - name: Commit changes
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add downloaded images"
          git push
