name: Merge release branch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release branch to be merged'
        required: true
        default: 'release-2022.01.0'

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Merge release branch
        run: |
          # Set variables
          GIT_URL="https://github.com/anvesh898" # Replace with your GitHub username
          RELEASE_NAME=${{ github.event.inputs.release_name }}
          TAG=$(echo "${RELEASE_NAME}" | awk -F"release-" '{print $2}')
          MASTER_BRANCH="master"
          
          # Fetch the latest changes
          git fetch
          
          # Check out the release branch
          git checkout "${RELEASE_NAME}"
          git pull origin "${RELEASE_NAME}"
          
          # Merge the release branch to master
          git checkout "${MASTER_BRANCH}"
          git pull origin "${MASTER_BRANCH}"
          git merge --no-ff "${RELEASE_NAME}"
          
          # Push the changes to the master branch
          git push --set-upstream origin "${MASTER_BRANCH}"
          
          # Create a tag and push it
          git tag "${TAG}" || echo "Tag already exists"
          git push --tags origin master:master
