name: Update Code1

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the zip file'
        required: true

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download code.zip
        run: curl -L ${{ github.event.inputs.url }} -o code.zip

      - name: Extract HTML source code
        run: unzip -p code.zip | grep -oP '(?<=href=")[^"]+(?=")' | grep -i zip | xargs curl -LO

      - name: Remove existing files
        uses: jakejarvis/gha-remove-files@master
        with:
          files: |
            **/*

      - name: Unzip new code
        run: unzip -q '*.zip'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update code'
          commit_options: '--no-verify'
