name: Create release branch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release branch to be created'
        required: true
        default: 'release-2022.01.0'
      repo_names:
        description: 'List of repository names to create the release branch in'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
      - name: Create release branch in each repository
        run: |
          # Set variables
          GIT_URL="https://github.com/anvesh898" # Replace with your GitHub username
          ORG_NAME="anvesh898" # Replace with your organization name
          RELEASE_NAME=${{ github.event.inputs.release_name }}
          REPO_NAMES=${{ github.event.inputs.repo_names }}
          
          # Check out the develop branch in each repository
          for REPO_NAME in ${REPO_NAMES}; do
            cd "$REPO_NAME"
            git fetch || { echo "Error fetching updates from remote repository" ; exit 1; }
            git checkout develop || { echo "Error checking out develop branch" ; exit 1; }
            git pull origin develop || { echo "Error updating develop branch" ; exit 1; }
            
            # Create a new branch from develop
            git branch "${RELEASE_NAME}" || { echo "Error creating release branch" ; exit 1; }
            git push --set-upstream origin "${RELEASE_NAME}" || { echo "Error pushing release branch to remote repository" ; exit 1; }
            cd ..
          done
