name: Create release branch

on:
  push:
    branches:
      - develop

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out parent repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Get repository list
        id: repo_list
        run: |
          # Read repository list from config file (replace with your own method of obtaining the list)
          REPO_LIST=$(cat config.txt)
          
          # Set the output variable
          echo "::set-output name=repo_list::${REPO_LIST}"
          
      - name: Create release branch
        run: |
          # Set variables
          GIT_URL="https://github.com/USERNAME" # Replace with your GitHub username
          ORG_NAME="ORGANIZATION" # Replace with your organization name
          RELEASE_NAME="release-2022.01.0" # Replace with desired release name
          
          # Get repository list from output of previous step
          REPO_LIST=${{ steps.repo_list.outputs.repo_list }}
          
          # Iterate over repositories
          for repo in ${REPO_LIST}; do
            # Clone repository if it doesn't already exist
            if [[ ! -d "$repo" ]]; then
              git clone "${GIT_URL}"/"${ORG_NAME}"/"${repo}" || exit 1
            fi
            cd "${repo}" || { echo "Can not access to ${repo}"; }
            
            # Fetch the latest changes
            git fetch
            
            # Check out the develop branch
            git checkout develop
            git pull origin develop
            
            # Create a new branch from develop
            git branch "${RELEASE_NAME}"
            git push --set-upstream origin "${RELEASE_NAME}"
            
            # Return to the top level directory
            cd ..
          done
