name: Create release branch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release branch to be created'
        required: true
        default: 'release-2022.01.0'

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository containing organization directory
        uses: actions/checkout@v2
        with:
          repository: 'cloud443/organization-repo' # Replace with the name of your repository
      - name: Print current working directory
        run: pwd
      - name: Change to organization directory
        run: |
          ORG_NAME="anvesh898" # Replace with your organization name
          cd "$ORG_NAME" || { echo "Error changing to organization directory" ; exit 1; }
      - name: Create release branch in each repository
        run: |
          # Set variables
          GIT_URL="https://github.com/cloud443" # Replace with your GitHub username
          ORG_NAME="anvesh898" # Replace with your organization name
          RELEASE_NAME=${{ github.event.inputs.release_name }}
          REPO_NAMES=$(cat repo-names.txt)
          
          # Check out the develop branch in each repository
          for REPO_NAME in ${REPO_NAMES}; do
            # Check if repository directory exists
            if [ ! -d "$REPO_NAME" ]; then
              echo "Repository directory does not exist: $REPO_NAME"
