name: Merge release branch
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release branch to be merged'
        required: true
        default: 'release-2022.01.0'

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Git config
        run: |
          git config --global user.email 'anveshreddythummala@gmail.com'
          git config --global user.name 'anvesh898'
          
      - name: Merge release branch
        run: |
          RELEASE_NAME=${{ github.event.inputs.release_name }}
          
          # Check out the release branch
          git fetch
          git checkout "${RELEASE_NAME}"
          git pull origin "${RELEASE_NAME}"
          
          # Check out the master branch
          git checkout master
          git pull origin master
          
          # Merge the release branch into master
          git merge "${RELEASE_NAME}"
          git push
          
          # Delete the release branch
          git branch -d "${RELEASE_NAME}"
          git push origin --delete "${RELEASE_NAME}"
