name: Auto Tag on Merge Approval

on:
  pull_request:
    types: [closed]

jobs:
  tag_on_merge_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: Get the latest tag (if available)
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "Latest tag: $latest_tag"
  
          # Check if the base branch is main
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            # Increment the tag if it's not empty
            if [ -n "$latest_tag" ]; then
              new_tag=$(python -c "version = list(map(int, '$latest_tag'.split('.'))); version[-1] += 1; print('.'.join(map(str, version)))")
  
              # Create and push the new tag
              git tag $new_tag
              git push origin $new_tag
            else
              echo "No existing tags found. Skipping tag incrementation."
              # Handle the case when there are no existing tags
              # Add your custom logic here
            fi
          fi
